### PR TITLE
fix/341-Recurring-weekly-meetings: Throw validation error and make it…

### LINKED ISSUE #341: Recurring weekly meetings: Incorrect times created when setting a start date/time before time of activity creation
Steps to reproduce:
1. Add a Zoom activity
2. Click on "This is a recurring meeting:
3. Select "Weekly" under Recurrence
4. Choose a date or time that is before the current date/time. For instance, it is currently 5:30p, Dec 8. I'll choose Dec 7, 12p.
5. Choose a day of the week - I'll choose Tuesdays.
6. Set other settings as needed.
7. Save activity.

Expected result:
Meetings are created beginning next Tuesday, noon.

Actual result:
Meetings are created beginning next Tuesday, 5:33p (the time when I confirmed my settings and created the activity). Subsequent meetings in that recurrence will also have the same incorrect time.

Tested this with daily and monthly recurrence, and it works as expected.

Tested this in versions v4.1.1 and v4.3.

### PR DESCRIPTION
**Pull request by rickbeasley**
… more descriptive

### CODE REVIEW

File: mod_form.php [hunk 1]
```diff
@@ -719,7 +719,19 @@ public function validation($data, $files) {
...
+            } else if ($data['duration'] > 150 * 60 * 60) {
+                $errors['duration'] = get_string('err_duration_too_long', 'zoom');
+            }
+        }
+        else if($data['recurring'] == 1 && $data['recurrence_type'] != ZOOM_RECURRINGTYPE_NOTIME)
+        {
+            // Make sure start date time (first potential date of next meeting) is in the future.
+            if ($data['start_time'] < strtotime('today')) {
+                $errors['start_time'] = get_string('err_start_time_past_recurring', 'zoom');
+            }
```
Comment (jrchamp) [inline mod_form.php:734]: The automatic checks failed because of the else if formatting. It needs to be "cuddled", but the "if" doesn't touch the parenthesis. Also, maintain the blank lines between separate logical conditionals.
```suggestion

            // Make sure duration is positive and no more than 150 hours.
            if ($data['duration'] <= 0) {
                $errors['duration'] = get_string('err_duration_nonpositive', 'zoom');
            } else if ($data['duration'] > 150 * 60 * 60) {
                $errors['duration'] = get_string('err_duration_too_long', 'zoom');
            }
        } else if ($data['recurring'] == 1 && $data['recurrence_type'] != ZOOM_RECURRINGTYPE_NOTIME) {
            // Make sure start date time (first potential date of next meeting) is in the future.
            if ($data['start_time'] < strtotime('today')) {
                $errors['start_time'] = get_string('err_start_time_past_recurring', 'zoom');
            }

```

**Review by jrchamp — DISMISSED** [review]
This applies the same start time and duration rules to recurring meetings that have a fixed time. When we go to solve #297 we'll want to evaluate what our options are for recurring meetings also.

**Comment by jrchamp** [comment]
@sgrandh3 When you have time, please confirm that this is working for you with recurring meetings (both with fixed times and no times).

**Review by jrchamp — APPROVED** [review]
Thanks @sgrandh3 for testing this and confirming that it is working!
