### PR TITLE
db: revert registration upgrade; fix tables that upgraded

### LINKED ISSUE #563: Database schema is not aligned - column 'registration'
Good day!

When I go to **Site Administration > Reports > Performance Overview**, I see the following message:

image

When I click on **Database Schema Check** or **More info**, I see the following details:

image

Details text from the above screenshot:

**Zoom**

    column 'registration' should be NOT NULL (I)
    column 'registration' has default 'NULL', expected '2' (I)

Additional information:

- PHP: 8.2
- Moodle: 4.3.2+
- Zoom meeting: v5.1.4 | 2023121400

Let me know if you need any additional information.

Best regards,

Michael Milette

### PR DESCRIPTION
**Pull request by jrchamp**
The registration field definition was unintentionally changed. Some users upgraded after that change and have the wrong database column settings. After upgrading again, those users will have the correct column settings.

Fixes #563 
Regression from #505

### CODE REVIEW

File: db/upgrade.php [hunk 1]
```diff
@@ -933,5 +933,19 @@ function xmldb_zoom_upgrade($oldversion) {
...
 
+    if ($oldversion < 2024012500) {
+        $table = new xmldb_table('zoom');
+        $field = new xmldb_field('registration', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, '2', 'option_auto_recording');
+
+        // Launch change of notnull for field registration.
+        $dbman->change_field_notnull($table, $field);
+
+        // Launch change of default for field registration.
+        $dbman->change_field_default($table, $field);
```
Comment (jrchamp) [inline db/upgrade.php:944]: Here's a hand-merged version of the generated PHP code from the XMLDB editor.
```suggestion
        // Changing nullability of field registration on table zoom to not null.
        // Changing the default of field registration on table zoom to 2.
        $table = new xmldb_table('zoom');
        $field = new xmldb_field('registration', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, '2', 'option_auto_recording');

        // Launch change of nullability for field registration.
        $dbman->change_field_notnull($table, $field);

        // Launch change of default for field registration.
        $dbman->change_field_default($table, $field);
```

Except for a couple comments, there's no appreciable changes.

As far as providing useful context, this comment suggestion is probably better:
```suggestion
        // Upgrading to v5.1.0 accidentally modified the zoom table's registration field, which should not be null and should default to 2.
        $table = new xmldb_table('zoom');
        $field = new xmldb_field('registration', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, '2', 'option_auto_recording');

        // Launch change of nullability for field registration.
        $dbman->change_field_notnull($table, $field);

        // Launch change of default for field registration.
        $dbman->change_field_default($table, $field);
```

**Review by armccoy — DISMISSED** [review]
Looks good!

**Review by armccoy — APPROVED** [review]
I SAID IT LOOKS GOOD!!
