### PR TITLE
444: retry on curl eof error

### LINKED ISSUE #444: curl end of file encountered while updating a meeting
This occurs in different place. For example the cron to update zoom meetings based on the activities stored (modified ?) in Moodle.
Here is an extact of the log : 
`Processing next Zoom meeting activity ...
  Zoom meeting ID: 84460771777
  Zoom meeting title: Évaluation et amélioration de pratique-S2-Scott Miller PhD-Traducteur Bill Walker- ENH-EN1M8-2022/23
  Zoom meeting activity URL: https://www.academy-lact.com/mod/zoom/view.php?n=317
  Moodle course ID: 414
  => Skipped Zoom meeting activity for Zoom meeting ID 84460771777 as unchanged
  => Updated tracking fields for Zoom meeting ID 84460771777

Processing next Zoom meeting activity ...
  Zoom meeting ID: 86573156048
  Zoom meeting title: Évaluation et amélioration de pratique-S3-Grégoire VITRY & Olivier BROSSEAU-ENH-EN1M8-2022/23
  Zoom meeting activity URL: https://www.academy-lact.com/mod/zoom/view.php?n=318
  Moodle course ID: 414
  **!! Error updating Zoom meeting activity for Zoom meeting ID 86573156048: moodle_exception: Erreur webservice Zoom : Encountered end of file**. in /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/mod/zoom/classes/webservice.php:265
Stack trace:
#0 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/mod/zoom/classes/webservice.php(763): mod_zoom_webservice->make_call('meetings/865731...')
#1 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/mod/zoom/classes/task/update_meetings.php(82): mod_zoom_webservice->get_meeting_webinar_info('86573156048', '0')
#2 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/lib/cronlib.php(248): mod_zoom\task\update_meetings->execute()
#3 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/lib/cronlib.php(120): cron_run_inner_scheduled_task(Object(mod_zoom\task\update_meetings))
#4 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/lib/cronlib.php(73): cron_run_scheduled_tasks(1672943401)
#5 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/admin/cli/cron.php(79): cron_run()
#6 {main}`

The first one is doing only "get" and everything went well (also in the zoom call log). The second is doint a "patch" to modify something in the meeting but it fails.

I've just switched from JWT to OAUTH authentification for the token build after updating to the last version of the plugin. But it does the same.

It's a pretty new behavior... to day or a couple of days ago. Everything went well those last months. We did not change anything on our server/Moodle. Our Moodle version is 3.9.15+ (Build: 20220714) and our php version is 7.3.26.

Is someone may have an idea of where it could come from ?

Edit : 
Actually the error is coming with a "get". I added some trace and here what I get : 
`Processing next Zoom meeting activity ...
  Zoom meeting ID: 84801689279
  Zoom meeting title: Groupe DU Paris 8 - Le Problem Solving et les 3 niveaux d'intervention - S2 - Claudette PORTELLI - Traducteur : Silvia SPOLAORE - EN1M2-2023/24
  Zoom meeting activity URL: https://www.academy-lact.com/mod/zoom/view.php?n=614
  Moodle course ID: 546
-- apchea --  méthode: get
-- apchea --  url: https://api.zoom.us/v2/meetings/84801689279
-- apchea --  data: Array
(
)

-- apchea --  response: {"uuid":"QByyTtr4TY6fBzMntN1pUA==","id":84801689279,"host_id":"Zik8i09WRiG0jdtJckNtTg","host_email":"zoom@lact.fr","assistant_id":"","topic":"Groupe DU Paris 8 - Le Problem Solving et les 3 niveaux d'intervention - S2 - Claudette PORTELLI - Traducteur : Silvia SPOLAORE - EN1M2-2023/24","type":2,"status":"waiting","start_time":"2023-10-17T12:00:00Z","duration":210,"timezone":"Europe/Paris","agenda":"","created_at":"2022-07-25T09:10:26Z","start_url":"https://lact-fr.zoom.us/s/84801689279?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMSIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJhdWQiOiJjbGllbnRzbSIsInVpZCI6IlppazhpMDlXUmlHMGpkdEpja050VGciLCJpc3MiOiJ3ZWIiLCJzayI6IjEwMTc1MDgxMzQ2NzAxMzkyMTMiLCJzdHkiOjEwMCwid2NkIjoidXMwMiIsImNsdCI6MCwibW51bSI6Ijg0ODAxNjg5Mjc5IiwiZXhwIjoxNjczMDA0Njg2LCJpYXQiOjE2NzI5OTc0ODYsImFpZCI6IjlEWVNDU0prUk1paDFtbkVHOHBacGciLCJjaWQiOiIifQ.0uiYR4akXkZokBuP3zZtHeMGEqmUVz_V2xCtSn4mtds","join_url":"https://lact-fr.zoom.us/j/84801689279","settings":{"host_video":false,"participant_video":false,"cn_meeting":false,"in_meeting":false,"join_before_host":false,"jbh_time":0,"mute_upon_entry":true,"watermark":false,"use_pmi":false,"approval_type":2,"audio":"both","auto_recording":"cloud","enforce_login":false,"enforce_login_domains":"","alternative_hosts":"spolaore@lact.fr;cportelli@lact.fr","alternative_host_update_polls":false,"close_registration":false,"show_share_button":false,"allow_multiple_devices":false,"registrants_confirmation_email":true,"waiting_room":false,"request_permission_to_unmute_participants":false,"global_dial_in_countries":["US"],"global_dial_in_numbers":[{"country_name":"US","number":"+1 5074734847","type":"toll","country":"US"},{"country_name":"US","number":"+1 5642172000","type":"toll","country":"US"},{"country_name":"US","city":"New York","number":"+1 6465588656","type":"toll","country":"US"},{"country_name":"US","number":"+1 6469313860","type":"toll","country":"US"},{"country_name":"US","number":"+1 6694449171","type":"toll","country":"US"},{"country_name":"US","city":"San Jose","number":"+1 6699006833","type":"toll","country":"US"},{"country_name":"US","number":"+1 6892781000","type":"toll","country":"US"},{"country_name":"US","number":"+1 7193594580","type":"toll","country":"US"},{"country_name":"US","number":"+1 2532050468","type":"toll","country":"US"},{"country_name":"US","city":"Tacoma","number":"+1 2532158782","type":"toll","country":"US"},{"country_name":"US","city":"Washington DC","number":"+1 3017158592","type":"toll","country":"US"},{"country_name":"US","number":"+1 3052241968","type":"toll","country":"US"},{"country_name":"US","number":"+1 3092053325","type":"toll","country":"US"},{"country_name":"US","city":"Chicago","number":"+1 3126266799","type":"toll","country":"US"},{"country_name":"US","city":"Houston","number":"+1 3462487799","type":"toll","country":"US"},{"country_name":"US","number":"+1 3602095623","type":"toll","country":"US"},{"country_name":"US","number":"+1 3863475053","type":"toll","country":"US"}],"registrants_email_notification":true,"meeting_authentication":false,"encryption_type":"enhanced_encryption","approved_or_denied_countries_or_regions":{"enable":false},"breakout_room":{"enable":false},"alternative_hosts_email_notification":true,"device_testing":false,"focus_mode":false,"enable_dedicated_group_chat":false,"private_meeting":false,"email_notification":true,"host_save_video_order":false},"pre_schedule":false}
  => Skipped Zoom meeting activity for Zoom meeting ID 84801689279 as unchanged
  => Updated tracking fields for Zoom meeting ID 84801689279
  

Processing next Zoom meeting activity ...
  Zoom meeting ID: 81550169849
  Zoom meeting title: Groupe DU Paris 8 - Le Problem Solving et les 3 niveaux d'intervention - S3 - Claudette PORTELLI - Traducteur : Silvia SPOLAORE - EN1M2-2023/24
  Zoom meeting activity URL: https://www.academy-lact.com/mod/zoom/view.php?n=615
  Moodle course ID: 546
-- apchea --  méthode: get
-- apchea --  url: https://api.zoom.us/v2/meetings/81550169849
-- apchea --  data: Array
(
)

-- apchea --  response: Encountered end of file
  !! Error updating Zoom meeting activity for Zoom meeting ID 81550169849: moodle_exception: Erreur webservice Zoom : Encountered end of file. in /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/mod/zoom/classes/webservice.php:269
Stack trace:
#0 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/mod/zoom/classes/webservice.php(767): mod_zoom_webservice->make_call('meetings/815501...')
#1 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/mod/zoom/classes/task/update_meetings.php(82): mod_zoom_webservice->get_meeting_webinar_info('81550169849', '0')
#2 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/lib/cronlib.php(248): mod_zoom\task\update_meetings->execute()
#3 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/lib/cronlib.php(120): cron_run_inner_scheduled_task(Object(mod_zoom\task\update_meetings))
#4 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/lib/cronlib.php(73): cron_run_scheduled_tasks(1672997401)
#5 /httpdjail/var/www/vhosts/academy-lact.com/httpdocs/admin/cli/cron.php(79): cron_run()
#6 {main}`

The first one is "ok", the second is an error. I can't see any difference.... Could it be the API rate limit reached ? we have several hundred meetings to update....

Capture

### PR DESCRIPTION
**Pull request by rickbeasley**
lcollong's fix looks good, I just re-used the self::MAX_RETRIES variable which seems suited to the purpose.

Fixes #444

### CODE REVIEW

File: classes/webservice.php [hunk 1]
```diff
@@ -268,6 +268,14 @@ private function make_call($path, $data = [], $method = 'get') {
         }
         $rawresponse = $this->make_curl_call($curl, $method, $url, $data);
 
+        $eofretries = 1;
+        while ($curl->get_errno() == 35 && $eofretries <= self::MAX_RETRIES) {
+            sleep(1);
+            debugging('retrying after curl error 35, retry attempt ' . $eofretries);
+            $eofretries++;
+            $rawresponse = $this->make_curl_call($curl, $method, $url, $data);
+        }
```
Comment (jrchamp) [inline classes/webservice.php:277]: I like how isolated the current version is, but I typically like to fold the base case into the process. If you like this suggestion, great! But it's not something that I'm going to require it, so please let me know your thoughts.
```suggestion

        $attempts = 0;
        do {
            if ($attempts > 0) {
                sleep(1);
                debugging('retrying after curl error 35, retry attempt ' . $attempts);
            }

            $rawresponse = $this->make_curl_call($curl, $method, $url, $data);
            $attempts++;
        } while ($curl->get_errno() === 35 && $attempts <= self::MAX_RETRIES);
```

Comment (rickbeasley) [reply classes/webservice.php:277]: I'm fine with the change, only possible issue is maintenance since it requires a little more skill to read.

**Review by jrchamp — APPROVED** [review]
Looks good! Thanks @sgrandh3 for testing this!
